import type {
  ImportDeviceSessionRecord,
  ImportDraftRecord,
  ImportReportSnapshot,
  ImportSourceNodeRecord,
  ImportTargetEndpointRecord,
} from '../data';

export const importFixtureLibraries = [
  { id: 'photo', name: '商业摄影资产库' },
  { id: 'video', name: '视频工作流资产库' },
];

export const importFixtureTargets: ImportTargetEndpointRecord[] = [
  {
    id: 'target-local',
    endpointId: 'node-local',
    label: '本地 NVMe 主盘',
    type: '本机磁盘',
    writable: true,
    availableSpace: '3.4 TB 可用',
    statusLabel: '可写',
    tone: 'success',
  },
  {
    id: 'target-nas',
    endpointId: 'node-nas',
    label: '影像 NAS 01',
    type: 'NAS/SMB',
    writable: true,
    availableSpace: '18.9 TB 可用',
    statusLabel: '可写',
    tone: 'success',
  },
];

export const importFixtureBrowserState = {
  sessionId: 'device-cfexpress-a',
  currentPath: '/',
  items: [
    {
      id: 'browser-folder-1',
      deviceSessionId: 'device-cfexpress-a',
      entryType: 'DIRECTORY' as const,
      name: 'A001',
      relativePath: 'A001',
      fileKind: '文件夹',
      modifiedAt: '2026-04-12T10:10:00Z',
      isHidden: false,
      hasChildren: true,
      targetEndpointIds: ['target-local'],
    },
    {
      id: 'browser-file-1',
      deviceSessionId: 'device-cfexpress-a',
      entryType: 'FILE' as const,
      name: 'cover.jpg',
      relativePath: 'cover.jpg',
      fileKind: '图片',
      size: '12 MB',
      modifiedAt: '2026-04-12T10:10:00Z',
      isHidden: false,
      hasChildren: false,
      targetEndpointIds: [],
    },
  ],
  total: 2,
  hasMore: false,
};

export const importFixtureDevices: ImportDeviceSessionRecord[] = [
  {
    id: 'device-cfexpress-a',
    deviceKey: 'cfexpress-a',
    deviceLabel: 'CFexpress A 卡（A 机位）',
    deviceType: '存储卡',
    libraryId: 'photo',
    mountPath: 'E:\\DCIM',
    connectedAt: '2026-04-12T10:08:00Z',
    connectedAtSortKey: 1008,
    lastSeenAt: '2026-04-12T10:10:00Z',
    capacitySummary: {
      total: '960 GB',
      available: '118 GB',
      usedPercent: 88,
    },
    scanStatus: '已完成',
    sessionStatus: '可导入',
    activeDraftId: 'draft-cfexpress-a',
    issueIds: [],
    fileCount: 4,
    folderCount: 1,
    duplicateCount: 0,
    exceptionCount: 0,
    description: '现场主机位素材。',
    availableTargetEndpointIds: ['target-local', 'target-nas'],
  },
  {
    id: 'device-audio',
    deviceKey: 'audio-usb',
    deviceLabel: '录音 U 盘（访谈音频）',
    deviceType: 'U 盘',
    libraryId: 'video',
    mountPath: 'F:\\Audio',
    connectedAt: '2026-04-12T08:34:00Z',
    connectedAtSortKey: 834,
    lastSeenAt: '2026-04-12T08:36:00Z',
    capacitySummary: {
      total: '256 GB',
      available: '41 GB',
      usedPercent: 84,
    },
    scanStatus: '已完成',
    sessionStatus: '异常待处理',
    activeDraftId: 'draft-audio',
    issueIds: ['issue-audio'],
    fileCount: 3,
    folderCount: 1,
    duplicateCount: 1,
    exceptionCount: 1,
    description: '音频素材导入需要处理冲突。',
    availableTargetEndpointIds: ['target-local'],
  },
];

export const importFixtureDrafts: ImportDraftRecord[] = [
  {
    id: 'draft-cfexpress-a',
    deviceSessionId: 'device-cfexpress-a',
    libraryId: 'photo',
    selectedFileIds: ['node-cf-1', 'node-cf-2'],
    targetEndpointIds: ['target-local', 'target-nas'],
    targetStrategy: '原片入本地与 NAS',
    precheckSummary: {
      blockingCount: 0,
      riskCount: 0,
      passedCount: 6,
      updatedAt: '2026-04-12T10:10:00Z',
      checks: {
        sourceReadable: 'passed',
        targetWritable: 'passed',
        capacityReady: 'passed',
        pathConflict: 'passed',
        deviceOnline: 'passed',
        executorReady: 'passed',
      },
      items: [
        { id: 'precheck-1', label: '来源可读', status: 'passed', detail: '目录读取正常。' },
      ],
    },
    lastEditedAt: '2026-04-12T10:10:00Z',
    hasBlockingIssues: false,
    status: '草稿中',
  },
  {
    id: 'draft-audio',
    deviceSessionId: 'device-audio',
    libraryId: 'video',
    selectedFileIds: ['node-audio-1'],
    targetEndpointIds: ['target-local'],
    targetStrategy: '先入本地',
    precheckSummary: {
      blockingCount: 1,
      riskCount: 0,
      passedCount: 5,
      updatedAt: '2026-04-12T08:36:00Z',
      checks: {
        sourceReadable: 'passed',
        targetWritable: 'passed',
        capacityReady: 'passed',
        pathConflict: 'blocking',
        deviceOnline: 'passed',
        executorReady: 'passed',
      },
      items: [
        { id: 'precheck-audio-1', label: '路径冲突', status: 'blocking', detail: '发现同名音频文件。' },
      ],
    },
    lastEditedAt: '2026-04-12T08:36:00Z',
    hasBlockingIssues: true,
    status: '草稿中',
  },
];

export const importFixtureSourceNodes: ImportSourceNodeRecord[] = [
  {
    id: 'node-cf-1',
    deviceSessionId: 'device-cfexpress-a',
    name: 'A001_C001_0329.mov',
    relativePath: 'A001/A001_C001_0329.mov',
    fileKind: '视频',
    size: '16.2 GB',
    status: '待导入',
    targetEndpointIds: ['target-local', 'target-nas'],
    issueIds: [],
  },
  {
    id: 'node-cf-2',
    deviceSessionId: 'device-cfexpress-a',
    name: 'A001_C001_0329_proxy.mp4',
    relativePath: 'A001/A001_C001_0329_proxy.mp4',
    fileKind: '视频',
    size: '2.1 GB',
    status: '待导入',
    targetEndpointIds: ['target-local'],
    issueIds: [],
  },
  {
    id: 'node-audio-1',
    deviceSessionId: 'device-audio',
    name: '访谈_环境底噪.wav',
    relativePath: 'Audio/roomtone.wav',
    fileKind: '音频',
    size: '218 MB',
    status: '冲突',
    targetEndpointIds: ['target-local'],
    issueIds: ['issue-audio'],
  },
];

export const importFixtureReports: ImportReportSnapshot[] = [
  {
    id: 'report-running',
    deviceSessionId: 'device-cfexpress-a',
    taskId: 'job-import-1',
    title: 'CFexpress A 卡（A 机位） / 刚提交的导入作业',
    status: '已排队',
    submittedAt: '2026-04-12T10:11:00Z',
    successCount: 0,
    failedCount: 0,
    partialCount: 0,
    verifySummary: '导入作业已创建，等待本地执行器执行。',
    targetSummaries: [
      {
        endpointId: 'target-local',
        label: '本地 NVMe 主盘',
        status: '等待执行',
        successCount: 0,
        failedCount: 0,
        transferredSize: '0 B',
      },
    ],
    issueIds: [],
    latestUpdatedAt: '2026-04-12T10:11:00Z',
    fileCount: 2,
  },
];
